import { useGenerator } from "../../stores/generatorStore";
import { useSettings } from "../../stores/settingsStore";
import { SecretPanel, usePanelRegenerate } from "../Panels/SecretPanel";
import { reportError } from "../../utils/reportError";
import { useEffect, useRef } from "react";

export function PasswordPanel() {
  const memorable = useSettings((s) => s.memorable_default);
  const setSettings = useSettings((s) => s.set);
  const secret = useGenerator((s) => s.password);
  const { regenerate, err } = usePanelRegenerate("password");
  const meta = memorable ? "mémorable FR · 14-20" : `${secret.length} chars · site-compat`;

  // Mode persistence only: regenerate when the memorable mode actually
  // changes after mount. useAutoGenerate (App) owns the boot generation;
  // regenerating here too raced the boot pipeline and could replace the
  // password that was auto-copied with a different one (display/clipboard
  // mismatch). The ref skips the mount run so a restart still shows the
  // persisted mode's secret generated by the boot pipeline.
  const prevMemorable = useRef(memorable);
  useEffect(() => {
    if (prevMemorable.current === memorable) return;
    prevMemorable.current = memorable;
    regenerate().catch((e) => reportError("panel mode regenerate", e));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [memorable]);

  const toggleMemorable = () => {
    const next = !memorable;
    // Persist the choice; the effect above triggers the regeneration.
    setSettings({ memorable_default: next });
  };

  return (
    <SecretPanel
      kind="password"
      meta={meta}
      regenerate={regenerate}
      err={err}
      footerControls={
        <div className="panel-mode">
          <label className="mode-toggle">
            <input type="checkbox" checked={memorable} onChange={toggleMemorable} />
            <span>Mot de passe mémorable (mots français) · Ctrl+M</span>
          </label>
        </div>
      }
    />
  );
}
